### ISSUE TITLE
E2E example with persistentVolumeReclaimPolicy: Delete doesn't work

### ISSUE THREAD

**Issue by raushan2016** [kubernetes-sigs/blobfuse-csi-driver#135]
PV create with `persistentVolumeReclaimPolicy: Delete` is failing with the error 
`Error getting deleter volume plugin for volume "pv-blobfuse": no volume plugin matched`

**What you expected to happen**:
PV should get deleted and the backing container should also get deleted.

**How to reproduce it**:
* Use the E2E example with SAS token.
* Create PV with `persistentVolumeReclaimPolicy: Delete`
* Delete the PVC.

**Anything else we need to know?**:
SAS token has all the RBAC permission

**Environment**:
- CSI Driver version: Master
- Kubernetes version (use `kubectl version`): v1.15.10
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): Linux my-nginx-f969cff84-2qprc 4.15.0-1071-azure #76-Ubuntu SMP Wed Feb 12 03:02:44 UTC 2020 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
@raushan2016 are you using static provioning: https://github.com/kubernetes-sigs/blobfuse-csi-driver/blob/master/deploy/example/e2e_usage.md#static-provisioninguse-an-existing-storage-account
We don't support delete volume if it's static provioning since the container is brought by user, it's user's responsibility to delete container.

We only support `persistentVolumeReclaimPolicy: Delete` in dynamic provisioning(by using storage class)
