### ISSUE TITLE
[test] set e2e test CI

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/blobfuse-csi-driver#9]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

**Comment by tall49er** [comment]
I would like to work on it.

**Comment by andyzhangx** [comment]
since blobfuse driver is already moved to the https://github.com/kubernetes-sigs org, could you also enable CI test in test-infra, thanks. 
@chewong 
cc @ritazh

**Comment by chewong** [comment]
To avoid making massive PRs like https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/118 and https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/166, I am going to separate the following tasks into individual PRs:
  - [x] Add blobfuse CI jobs in k/test-infra (https://github.com/kubernetes/test-infra/pull/15515)
  - [ ] Create aks-engine API model for e2e test instead of relying on API model in cloud-provider-azure
  - [ ] Change repo prefix from `github.com` to `sigs.k8s.io`
  - [ ] Fix any error when running unit test and code verification in prow and add `verify-helm-chart.sh` as part of code verification test
  - [ ] Fix any error when running sanity and integration test in prow
  - [ ] Fix any error when running e2e test in prow

**Comment by chewong** [comment]
@andyzhangx for e2e test, do you have a preference on which k8s version to test on, and whether we should use VM with AS or VMSS, or both?
